### ISSUE TITLE
Add pytest-order to nixpkgs

### ISSUE THREAD

**Issue by jacg** [mrbean-bremen/pytest-order#5]
I'm trying to [add](https://github.com/NixOS/nixpkgs/pull/110141) `pytest-order` to `nixpkgs` (the collection of software installable with the [Nix package manager](https://nixos.org/)).

In the process I'm getting the following two test failures:

```
=================================== FAILURES ===================================
_______________________________ test_quickstart ________________________________

item_names_for = <function item_names_for.<locals>._item_names_for at 0x7ffff528c5f0>

    def test_quickstart(item_names_for):
        test_content = """
        import pytest

        def test_foo():
            pass

        def test_bar():
            pass
        """
>       assert item_names_for(test_content) == ["test_foo", "test_bar"]

/build/source/tests/test_ordering.py:330:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

tests_content = '\n    import pytest\n\n    def test_foo():\n        pass\n\n    def test_bar():\n        pass\n    '

    def _item_names_for(tests_content):
        items = testdir.getitems(tests_content)
        hook = testdir.config.hook
>       hook.pytest_collection_modifyitems(session=items[0].session,
                                           config=testdir.config, items=items)
E       IndexError: list index out of range

/build/source/tests/conftest.py:13: IndexError
----------------------------- Captured stdout call -----------------------------
============================= test session starts ==============================
platform linux -- Python 3.7.9, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: /build/pytest-of-nixbld/pytest-0/test_quickstart0
plugins: order-0.9.3, xdist-2.1.0, forked-1.3.0, dependency-0.5.1, mock-3.3.1
collected 0 items

============================ no tests ran in 0.01s =============================
________________________________ test_relative _________________________________

item_names_for = <function item_names_for.<locals>._item_names_for at 0x7ffff5306170>

    def test_relative(item_names_for):
        test_content = """
        import pytest

        @pytest.mark.order(after="test_second")
        def test_third():
            pass

        def test_second():
            pass

        @pytest.mark.order(before="test_second")
        def test_first():
            pass
        """
>       assert item_names_for(test_content) == ["test_first", "test_second",
                                                "test_third"]

/build/source/tests/test_relative_ordering.py:30:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

tests_content = '\n    import pytest\n\n    @pytest.mark.order(after="test_second")\n    def test_third():\n        pass\n\n    def test_second():\n        pass\n\n    @pytest.mark.order(before="test_second")\n    def test_first():\n        pass\n    '

    def _item_names_for(tests_content):
        items = testdir.getitems(tests_content)
        hook = testdir.config.hook
>       hook.pytest_collection_modifyitems(session=items[0].session,
                                           config=testdir.config, items=items)
E       IndexError: list index out of range

/build/source/tests/conftest.py:13: IndexError
----------------------------- Captured stdout call -----------------------------
============================= test session starts ==============================
platform linux -- Python 3.7.9, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: /build/pytest-of-nixbld/pytest-0/test_relative0
plugins: order-0.9.3, xdist-2.1.0, forked-1.3.0, dependency-0.5.1, mock-3.3.1
collected 0 items

============================ no tests ran in 0.01s =============================
=========================== short test summary info ============================
FAILED tests/test_ordering.py::test_quickstart - IndexError: list index out o...
FAILED tests/test_relative_ordering.py::test_relative - IndexError: list inde...
========================= 2 failed, 88 passed in 6.62s =========================
```

As I'm not familiar with the code, it's not obvious to me what might be causing this. Does this ring any bells? Can you provide any suggestions?

**Comment by mrbean-bremen** [comment]
Hm, it looks as if `testdir.items` returns an empty list - out of the box I don't see how this can happen. 
I fixed a problem with pytest 6.2 in master, but with pytest 6.1 all CI tests pass in the released version. I'm not familiar with NixOS - the CI tests pass under Ubuntu, MacOS and Windows, including the pytest 6.1.2 / Python 2.7.9 combination, so something else must be different in the environment... 
I will check if I can find anything, and thanks for the report!

**Comment by mrbean-bremen** [comment]
@jacg - currently the tests are not shipped with the package. This is something that I can change, if needed - actually, I will probably do this anyway, as it is the standard nowadays.
Can you show me how are you executing the tests? In the CI, they are executed via tox, maybe you are calling them some other way?

**Comment by jacg** [comment]
> currently the tests are not shipped with the package.

Yes, I noticed, as it created a little hoop I had to jump through: the Nix machinery caters for packages available on PyPI, and that is simplest way of packaging Python packages in Nix. To get at the tests I had to use a slightly more involved approach that fetches from GitHub.

> This is something that I can change, if needed

It would simplify things a little at my end (and maybe even solve the problem with the tests?).

> Can you show me how you are executing the tests?

Hmm, the Nix machinery is taking charge of running the tests, with its `pytestCheckPhase`, which is defined [here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/interpreters/python/hooks/pytest-check-hook.sh#L29-L44)

> In the CI, they are executed via tox, maybe you are calling them some other way?

It appears not to be using tox.

I'll try to dig a bit deeper when I have some time.

**Comment by mrbean-bremen** [comment]
Ok, thanks - I can make a patch release now with the tests in the source package, if that helps you.

**Comment by jacg** [comment]
That seems to have done the trick: the tests pass locally. I have updated the PR in `nixpkgs`. With a bit of luck it will be accepted soon. I'll update you (and close this issue) when that happens.

**Comment by jacg** [comment]
`pytest-order` has now been accepted into `nixpkgs`.

Thanks for your help.
