### ISSUE TITLE
Keep groups of tests together

### ISSUE THREAD

**Issue by ThePraeceps** [mrbean-bremen/pytest-order#6]
Hey,

In my applications my module level fixtures have a significant time cost (30+ seconds per test), and currently this plugin correctly orders the depedencies but unnecessarily splits up the modules.

Could you add an argument to set the level at which you want the ordering to be done i.e. the largest group it can move - function, class, module.

Thanks!

**Comment by mrbean-bremen** [comment]
If I understand you correctlty, you can use the [order-scope option](https://mrbean-bremen.github.io/pytest-order/dev/#order-scope). Use `--order-scope=module` on the command line, or put the option in your `pytest.ini` to handle sorting separately for each module.

**Comment by ThePraeceps** [comment]
Hey,

I almost want the exact opposite. Each of my test modules uses a common dependency to check that something can be loaded, and each function in the module depends on the function before it.

This results in each function being reordered so that the loading test is done, then all the first functions in each of those modules gets done, then the second function and so on.

 I want the modules to be reordered, but not the functions (because i already wrote those in the correct order)

**Comment by mrbean-bremen** [comment]
Ah, so you want to sort only your test modules, but not tests inside the modules. Ok, that is currently only possible by adding a sort marker to each test in each module, with contiguous numbering.
This is inconvenient - I will think about an option, thanks for the suggestion!

**Comment by mrbean-bremen** [comment]
@ThePraeceps - I added a new option [group-order-scope](https://mrbean-bremen.github.io/pytest-order/dev/#order-group-scope) in master, please check if this is what you need.

**Comment by ThePraeceps** [comment]
Looks good! My orders are based on dependencies however so it still gets rearranged.

**Comment by mrbean-bremen** [comment]
Ok, I was planning to add support for relative markers as a next step anyway, will see if I get something done over the weekend. Are you using relative order markers, or are you using `pytest-dependency`?

**Comment by ThePraeceps** [comment]
I'm using `pytest-dependency` :)

**Comment by mrbean-bremen** [comment]
Ok, so you are using `pytest-dependency` with the `order-dependencies` option, right? Good to know that someone actually uses this!
I was planning to first add support for `order` relative markers, and afterwards check the dependency markers. This may take a while...

**Comment by ThePraeceps** [comment]
Yeah, exactly! Surprised it's not a thing it does natively, seems odd to have tests skip because they haven't run yet.

**Comment by mrbean-bremen** [comment]
There is a [PR](https://github.com/RKrahl/pytest-dependency/pull/44) for this - if that's get merged, the option in `pytest-order` won't probably be needed anymore.

**Comment by mrbean-bremen** [comment]
@ThePraeceps - I added something to master, though I may still have to clean it up a bit and add a few tests. Note that dependency markers in session scope (e.g. markers referencing a different module) it is currently only tested for named markers, e.g. if you set the name in one module and reference that name in the other module, instead of the fully qualified path (which will probably not work, I will address this later). I would be interested to know it this works for you.

**Comment by ThePraeceps** [comment]
@mrbean-bremen  as in you want me to name the dependency marker, then make a dependency on rather than test-test.py::test_func ?

**Comment by mrbean-bremen** [comment]
Yes, that is what I mean. You can try with the current markers, but I suspect it will not work. I may have another look at this over the weekend.

**Comment by mrbean-bremen** [comment]
Ok, this took longer than I had hoped. `pytest-dependency` uses the nodeid of tests in session scope, but it can differ between different pytest versions - so testing this was a bit of a problem. In my earlier tests I had not set the session scope, so they could not have worked...
Anyway, it should mostly work now in master. @ThePraeceps - can you please test if it works for you? You will need the option `--order-group-scope=module` for your case.

**Comment by ThePraeceps** [comment]
I can confirm the master branch achieves the effect I wanted precisely! Great work :)

**Comment by mrbean-bremen** [comment]
FYI: I made a new release that contains the changes.
